# Generated by Django 6.0.6 on 2026-06-22 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_movie_actors_alter_movie_genres_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='datetime',
            new_name='created_at',
        ),
    ]
